server:
  port: 8002
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
mensagem: mensajePruebaCatalog

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: catalog
      username: root
      password: root
      authentication-database: admin

  resilience4j:
    circuitbreaker:
      instances:
        series:
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          failureRateThreshold: 50
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 15000
          permittedNumberOfCallsInHalfOpenState: 3
          registerHealthIndicator: true
          allowHealthIndicatorToFail: false  
