server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
mensagem: mensajePruebaMovie

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
