server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
mensagem: mensajePruebaSerie

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: series
      username: root
      password: root
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
