server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/marielagcw/final-especialidad-back1.git
